### ISSUE TITLE
[feat] iterate on multiple HySE

### ISSUE THREAD

**Issue by Gitcatmeoww** [Gitcatmeoww/HITS-system-implementation#16]
In PR #15 , we implemented the first version of multiple HySE search. Specifically, in the multiple-table retrieval stage, we generated `N-1` hypothetical schemas that could jointly solve the task.

However, this approach is impractical when `N` is relatively large (e.g., 10), as it assumes that 9 normalized tables could jointly solve the task.

**Proposed Iteration**
To address this, we propose an iterative and dynamic multiple-table approach. Instead of naively generating `N-1` multi-table HySE, we will use a dynamic prompt to generate a set of schemas that could solve the task. The number of schemas generated (`m`) will be randomly sampled from a range of 1 to `num_left`.

**Complete Logic**
- Define Number of Schemas (N):
  - `num_schema` specifies the number of schemas required for the search
  - Initialize `num_left` to `num_schema`

- Single Table Approach:
  - Generate a single denormalized schema and retrieve results
  - Update `num_left` by decrementing it by 1

- Multiple Table Approach:
  - Use a dynamic prompt to generate a set of schemas that could solve the task. The number of schemas generated (m) is randomly sampled from a range of 1 to `num_left`
  - Retrieve results for each generated schema
  - Update `num_left` by decrementing it by `m`
  - Repeat until `num_left` is zero

- Return Results:
  - Aggregate and return the results, sorted by cosine similarity, keeping the top `k` results

**Comment by madelonhulsebos** [comment]
This resembles well what we have discussed! There are different strategies to distribute k over the retrieved tables, indeed, but we agreed that it is a good starting point for our implementation to just return top-k based on highest cosine similarity now.
